name: Playwright Daily Automation

on:
  schedule:
    - cron: '30 2 * * *'   # Daily 8:00 AM IST
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run nivesh-playwright tests
        run: |
          cd nivesh-playwright
          npm install
          npx playwright install --with-deps
          npx playwright test

      - name: Run nivesh-partner tests
        run: |
          cd nivesh-partner
          npm install
          npx playwright install --with-deps
          npx playwright test

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            nivesh-playwright/playwright-report
            nivesh-partner/playwright-report

      # ðŸ”¥ ZIP REPORT
      - name: Zip Playwright Reports
        if: always()
        run: |
          zip -r playwright-report.zip nivesh-playwright/playwright-report nivesh-partner/playwright-report

      # ðŸ“§ EMAIL WITH ATTACHMENT
      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Playwright Daily Automation Report"
          body: |
            Hi Sir,

            Daily Playwright automation has been executed.

            Please find the attached Playwright HTML report.

            Regards,
            Tanuj
          to: |
            jangratanuj999@gmail.com,
            girishgargdce@gmail.com
          from: Playwright Automation <jangratanuj999@gmail.com>
          attachments: playwright-report.zip
